#!/bin/bash

set -eu

PHP_VERSION="${PHP_VERSION:-8.4}"
IMAGE_NAME="appsignal-php-integration-vanilla-${PHP_VERSION}"

docker build \
  --build-arg PHP_VERSION="$PHP_VERSION" \
  -f tests/Integration/vanilla/Dockerfile \
  -t "$IMAGE_NAME" .

docker run --rm "$IMAGE_NAME"
